// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ecommerce/ordermanagement/ordermanagement.proto

package ordermanagement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PENDING    Status = 0
	Status_PROCESSING Status = 1
	Status_SHIPPED    Status = 2
	Status_DELIVERED  Status = 3
	Status_CANCELLED  Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "SHIPPED",
		3: "DELIVERED",
		4: "CANCELLED",
	}
	Status_value = map[string]int32{
		"PENDING":    0,
		"PROCESSING": 1,
		"SHIPPED":    2,
		"DELIVERED":  3,
		"CANCELLED":  4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ecommerce_ordermanagement_ordermanagement_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_ecommerce_ordermanagement_ordermanagement_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP(), []int{0}
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerUnit  float64                `protobuf:"fixed64,3,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// NEW: Represents a single event in the order's shipping history.
type ShipmentEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Description    string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Location       string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	EventTimestamp int64                  `protobuf:"varint,3,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP(), []int{2}
}

func (x *ShipmentEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShipmentEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ShipmentEvent) GetEventTimestamp() int64 {
	if x != nil {
		return x.EventTimestamp
	}
	return 0
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CustomerId      string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddress *Address               `protobuf:"bytes,3,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderId            string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId         string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items              []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddress    *Address               `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	TotalPrice         float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status             Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=ecommerce.Status" json:"status,omitempty"`
	CreatedAtTimestamp int64                  `protobuf:"varint,7,opt,name=created_at_timestamp,json=createdAtTimestamp,proto3" json:"created_at_timestamp,omitempty"`
	// repeated field in the response.
	ShipmentHistory []*ShipmentEvent `protobuf:"bytes,8,rep,name=shipment_history,json=shipmentHistory,proto3" json:"shipment_history,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *Order) GetCreatedAtTimestamp() int64 {
	if x != nil {
		return x.CreatedAtTimestamp
	}
	return 0
}

func (x *Order) GetShipmentHistory() []*ShipmentEvent {
	if x != nil {
		return x.ShipmentHistory
	}
	return nil
}

var File_ecommerce_ordermanagement_ordermanagement_proto protoreflect.FileDescriptor

const file_ecommerce_ordermanagement_ordermanagement_proto_rawDesc = "" +
	"\n" +
	"/ecommerce/ordermanagement/ordermanagement.proto\x12\tecommerce\"l\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12$\n" +
	"\x0eprice_per_unit\x18\x03 \x01(\x01R\fpricePerUnit\"\x80\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"v\n" +
	"\rShipmentEvent\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12'\n" +
	"\x0fevent_timestamp\x18\x03 \x01(\x03R\x0eeventTimestamp\"\xa0\x01\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.ecommerce.OrderItemR\x05items\x12=\n" +
	"\x10shipping_address\x18\x03 \x01(\v2\x12.ecommerce.AddressR\x0fshippingAddress\"\xf1\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.ecommerce.OrderItemR\x05items\x12=\n" +
	"\x10shipping_address\x18\x04 \x01(\v2\x12.ecommerce.AddressR\x0fshippingAddress\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.ecommerce.StatusR\x06status\x120\n" +
	"\x14created_at_timestamp\x18\a \x01(\x03R\x12createdAtTimestamp\x12C\n" +
	"\x10shipment_history\x18\b \x03(\v2\x18.ecommerce.ShipmentEventR\x0fshipmentHistory*P\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\v\n" +
	"\aSHIPPED\x10\x02\x12\r\n" +
	"\tDELIVERED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x042S\n" +
	"\x0fOrderManagement\x12@\n" +
	"\vCreateOrder\x12\x1d.ecommerce.CreateOrderRequest\x1a\x10.ecommerce.Order\"\x00B<\n" +
	"\x1dcom.ecommerce.ordermanagementP\x01Z\x19ecommerce/ordermanagementb\x06proto3"

var (
	file_ecommerce_ordermanagement_ordermanagement_proto_rawDescOnce sync.Once
	file_ecommerce_ordermanagement_ordermanagement_proto_rawDescData []byte
)

func file_ecommerce_ordermanagement_ordermanagement_proto_rawDescGZIP() []byte {
	file_ecommerce_ordermanagement_ordermanagement_proto_rawDescOnce.Do(func() {
		file_ecommerce_ordermanagement_ordermanagement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_ordermanagement_ordermanagement_proto_rawDesc), len(file_ecommerce_ordermanagement_ordermanagement_proto_rawDesc)))
	})
	return file_ecommerce_ordermanagement_ordermanagement_proto_rawDescData
}

var file_ecommerce_ordermanagement_ordermanagement_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ecommerce_ordermanagement_ordermanagement_proto_goTypes = []any{
	(Status)(0),                // 0: ecommerce.Status
	(*OrderItem)(nil),          // 1: ecommerce.OrderItem
	(*Address)(nil),            // 2: ecommerce.Address
	(*ShipmentEvent)(nil),      // 3: ecommerce.ShipmentEvent
	(*CreateOrderRequest)(nil), // 4: ecommerce.CreateOrderRequest
	(*Order)(nil),              // 5: ecommerce.Order
}
var file_ecommerce_ordermanagement_ordermanagement_proto_depIdxs = []int32{
	1, // 0: ecommerce.CreateOrderRequest.items:type_name -> ecommerce.OrderItem
	2, // 1: ecommerce.CreateOrderRequest.shipping_address:type_name -> ecommerce.Address
	1, // 2: ecommerce.Order.items:type_name -> ecommerce.OrderItem
	2, // 3: ecommerce.Order.shipping_address:type_name -> ecommerce.Address
	0, // 4: ecommerce.Order.status:type_name -> ecommerce.Status
	3, // 5: ecommerce.Order.shipment_history:type_name -> ecommerce.ShipmentEvent
	4, // 6: ecommerce.OrderManagement.CreateOrder:input_type -> ecommerce.CreateOrderRequest
	5, // 7: ecommerce.OrderManagement.CreateOrder:output_type -> ecommerce.Order
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ecommerce_ordermanagement_ordermanagement_proto_init() }
func file_ecommerce_ordermanagement_ordermanagement_proto_init() {
	if File_ecommerce_ordermanagement_ordermanagement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_ordermanagement_ordermanagement_proto_rawDesc), len(file_ecommerce_ordermanagement_ordermanagement_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecommerce_ordermanagement_ordermanagement_proto_goTypes,
		DependencyIndexes: file_ecommerce_ordermanagement_ordermanagement_proto_depIdxs,
		EnumInfos:         file_ecommerce_ordermanagement_ordermanagement_proto_enumTypes,
		MessageInfos:      file_ecommerce_ordermanagement_ordermanagement_proto_msgTypes,
	}.Build()
	File_ecommerce_ordermanagement_ordermanagement_proto = out.File
	file_ecommerce_ordermanagement_ordermanagement_proto_goTypes = nil
	file_ecommerce_ordermanagement_ordermanagement_proto_depIdxs = nil
}
